### ISSUE TITLE
Update Feed Configuration

### ISSUE THREAD

**Issue by araskachoi** [ChainSafe/chainlink-cosmos#106]
Upgrade Proposal:
"A configuration for each price feed the module supports. This config must include:
 \ - feed identifier and description
 \ - initial owner account for each feed
 \ - `A VALIDATION PURE FUNCTION THAT TAKES THE CURRENT AND PREVIOUS ROUND NUMBERS AS WELL AS THE CURRENT AND PREVIOUS DATA VALUES AND RETURNS A BOOLEAN IF THE PROPOSED NEW DATA IS VALID`"

![Screen Shot 2021-07-26 at 3.23.18 PM.png](https://images.zenhubusercontent.com/5f42c333eda7bd53f1bea9da/5665affb-9eb9-4a9d-9686-f4f7e7ce51b3)

  - will need to add this pure function to the configuration
  - update the proto + msg.go files

  - TBD: need to discuss with the chainlink team to understand what sort of function will be passed as a configuration parameter
    - practically, store the `pure function` as a byte array? encode/decode it using proto?

**Comment by freddyli7** [comment]
This will not be a `pure` function, instead, we need to add a `validation` interface in feed data submission tx. This validation interface should be able to do whatever the validation is against external resources, and it should be configurable. The submission flow continues regardless wether validation pass or not.
