### ISSUE TITLE
Implement `MultiFeed`

### ISSUE THREAD

**Issue by araskachoi** [ChainSafe/chainlink-cosmos#11]
The module must be able to manage multiple oracle sets and data providers

**THERE WILL ONLY EVER BE ONE INSTANCE OF THE MODULE PER APPLICATION**

Only whitelisted data providers could submit data to a particular feed. So the whitelist is per-feed if that makes sense

Description: the module should allow for multiple feeds that are managed by a `feedOwner`. Any `feedData` should only be allowed to push data if the user is part of the `dataProvider` list.

Acceptance Criteria:
feedData is only allowed to be pushed by dataProvider. the data is ingested and stored correctly

**Comment by freddyli7** [comment]
I think we've done this one.
