### ISSUE TITLE
The leader should receive ADDITIONAL compensation to cover gas costs

### ISSUE THREAD

**Issue by freddyli7** [ChainSafe/chainlink-cosmos#122]
we have with a very “loose” gas fee structure, but need to add the logic of compensate gas cost for `leader`.

**Comment by freddyli7** [comment]
found where `--fees` flag is when node started

**Comment by araskachoi** [comment]
![Screen Shot 2021-08-24 at 9 42 45 AM](https://user-images.githubusercontent.com/13338103/130656553-9c42c825-9ae6-4506-8467-6a0edb0565fe.png)
exists as a flag
