### ISSUE TITLE
Exposes FeedViewKeeper for consumption by other modules.

### ISSUE THREAD

**Issue by freddyli7** [ChainSafe/chainlink-cosmos#123]
According to the proposal, we need to `Exposes FeedViewKeeper for consumption by other modules`

In `/x/exported` package, there are some TODOs left, need to make sure we meet the requirement and test it. If not, we need to finish this feature.

**Comment by araskachoi** [comment]
ask willem about more context and information.

**Comment by willemolding** [comment]
I'm not the most experienced Go or Cosmos SDK developer, but as long as you can import the keeper defined in the `/x/chainlink/keeper/keeper.go` into another Cosmos SDK module and call methods on it then this is satisfied.

I'd say from looking at it that this is already the case

**Comment by LuaxY** [comment]
I have tried to modify existing bank module to access chainlink keeper from it.
I'm able to query different store using keeper methods like `GetFeed`, `GetLatestRoundId`, `GetLatestRoundFeedDataByFilter`

E.g:

```
3:02PM INF AAAAAA feed="this is test feed 1" module=x/bank
3:02PM INF BBBBBB module=x/bank round=1
3:02PM INF CCCCCC data="Context:\"1\" Oracles:\"\\367\\353=\\324\\243\\332\\246K\\324\\333\\267\\317\\033\\007Ll \\357\\317\\000\" Observations:<data:\"f\" > Observations:<data:\"e\" > Observations:<data:\"e\" > Observations:<data:\"d\" > Observations:<data:\" \" > Observations:<data:\"1\" > Observations:<data:\" \" > Observations:<data:\"t\" > Observations:<data:\"e\" > Observations:<data:\"s\" > Observations:<data:\"t\" > Observations:<data:\" \" > Observations:<data:\"d\" > Observations:<data:\"a\" > Observations:<data:\"t\" > Observations:<data:\"a\" > " module=x/bank
```
