### ISSUE TITLE
Implement Signature Validation Logic

### ISSUE THREAD

**Issue by araskachoi** [ChainSafe/chainlink-cosmos#132]
Currently, there is no validation for the signatures. it is stored as an array of byte arrays (`[][]byte`) and there is no validation logic tied to this. it can be stored as is.

Improvement proposal:
Chainlink Account Store has signing keys stored now.
Should tie this logic to verify feed data submissions have correct signatures.
should verify that the feed submitter has a valid chainlink account before submission. (done in ante?)

**Comment by araskachoi** [comment]
we will need a few things for validation.
OCR should include the following:
1. observation data
2. signed obversations
3. list of chainlink public keys
4. list of cosmos public keys

from the signed observations and observation, we can derive the `signature`. Then we will use the chainlink public key to verify the `signature`

**Comment by freddyli7** [comment]
we need:
1. OCR report which contains the observation signatures of the current round
2. data providers chainlink account pubkeys of the current round
3. the original observation data of the current round
4.data providers cosmos account pubkeys of the current round
