### ISSUE TITLE
Reformat CLI command name using kebab case

### ISSUE THREAD

**Issue by LuaxY** [ChainSafe/chainlink-cosmos#134]
Cosmos SDK and Tendermint use kebab case (word-word-word) for name of commands for the CLI but in Chainlink module we are using camel case (wordWordWord).

In order to have consistent commands name with the rest of the ecosystem, we should rename commands.

E.g:

```
addFeed -> add-feed
addDataProvider -> add-data-provider
addModuleOwner -> add-module-owner
```

We should also fix the different scripts and CLI tests with the new commands name

**Comment by freddyli7** [comment]
yeah we definitely need to do it!
