### ISSUE TITLE
Modify Validator Set

### ISSUE THREAD

**Issue by araskachoi** [ChainSafe/chainlink-cosmos#65]
Description:
A "validator set" can be modified using a cosmos transaction

Acceptance Criteria:

**Comment by freddyli7** [comment]
validator here means feed data providers.

impl tx that allows feed owner to add/remove data provider for a feed.

only feed owner is able to sign this tx

**Comment by LuaxY** [comment]
Do the tx allow to add/remove just one validator at time or multiples?
If multiples, in case of removing, if one the the validator does not already existe, do we want to fail all the tx or ignore it?

**Comment by LuaxY** [comment]
Update: based on proposal document, it's just one at a time.
