### ISSUE TITLE
New Round Tx

### ISSUE THREAD

**Issue by araskachoi** [ChainSafe/chainlink-cosmos#66]
Description:
The owner can submit a cosmos message transaction to force a new round.

* note: not sure if this is what is being referred to on the SOW. I dont understand why a transaction has to be made to "inform providers of a new round". will need to establish who the "data provider" is (if it is on the cosmos network user or if it is on chainlink network)

Acceptance Criteria:
- send a cosmos transaction to force a new round for every feed
- emit an event (#15)

**Comment by LernaJ** [comment]
Ask chainlink team how they would like the event to be handled; more information around the event trigger.
