### ISSUE TITLE
BUG: ModuleOwner can add themselves

### ISSUE THREAD

**Issue by araskachoi** [ChainSafe/chainlink-cosmos#93]
Description:
No check if there is already the module owner that already exists in the list of ModuleOwners

Steps to reproduce:
1. bash scripts/start.sh
2. chainlinkd tx chainlink addModuleOwner "$(chainlinkd keys show alice -a)" "$(chainlinkd keys show alice -p)" --from alice --keyring-backend test --chain-id testchain

**Comment by freddyli7** [comment]
module store takes account address as the key, so even if the existing module owners try to add themselves, there wont be duplication in the store I think, which means the tx modifies nothing in store but just pay the fee to the chain validators

**Comment by araskachoi** [comment]
![image](https://user-images.githubusercontent.com/13338103/126540533-f6139813-8156-4954-9200-ae527fbcaeeb.png)
